#! /bin/bash
# first argument is input file name generated by sort
# second argument is RRD_BATCH_ID
# third argument is Input file directory


awk -F"~" '{print $1 $2 $4 }' $3/$1 > $3/temp.$2
 RETCODE=$?
 
  if [ $RETCODE -ne 0 ] ;
  then 
  echo "unable to remove sortkey from the sorted input file for batch - " $2
  exit 1
  fi

cat $3/temp.$2 > $3/$1
 
 RETCODE=$?
 
 if [ $RETCODE -ne 0 ] ;
 then 
 echo "unable to overwrite this file - "  $2
 exit 1
 fi

rm $3/*.$2
