./startetlworkflow.sh workflow=wf_DS_DW_Firm_Team_Dim \
folder='Data Services' \
batch=rjm_1 \
context=P \
po_id=80000 \
dbconnection_ds=C57_DS \
dbconnection_dw=C57_DW \
p_workflow=wf_DWBUILD_Activity2 \
eod_flg=2
