#1. Environment parameter: lower case (dv, it, i2, qa, q2 ,p2, i01, mo......) 
#	2. Folder and workflow names should be in the same case as in Informatica
#	3. Run mode parameters: lower case 
#	 $HOME/server/ExtProc/sh_dss_firstrate_securityaudit.sh $HOME/server/TgtFiles/performance/$$OUTPUT_DTLFILE $HOME/server/TgtFiles/performance/$$OUTPUT_TGTFILE
#        $HOME/server/ExtProc/sh_dss_firstrate_securityaudit.sh   
# Assumption:	
#	1. The Column Header File should be available in specified location. 
#	   $HOME/server/TgtFiles/dw_ip_securityaudit_ColHdr.out
#	2. The DEtail Data file will be generated by ETL session for availability.
#          $HOME/server/TgtFiles/{firm_id}_caevent_detail.out
#	3. This script is used to be called in IP workflow wf_DW_IP_AccountingData
#	   in c_m_DW_IP_Securities immediately after detail data file is generated 
#         
###################################################################################

#!/bin/sh 
#echo 'execution started'
if [ -s $1 ]
then 
cat $PMTargetFileDir/dw_ip_securityaudit_ColHdr.out $1 > $2
else  
	if [ -s $2 ]
	    then
		rm $2
	fi
fi 
#echo 'execution completed' 
