###################################################################################
#
# This script can be used to manage ColHdr file individual workflow SD, QA or IT
# Author: 	SanjayWathore
# Date Created: 06/29/07
# Modified by:	None 
# Date Modified:None
#
#
# Description:  -Script concats the Column Header and Detail Data file only   
#		 when there is data available in Detail file and generate 
#		 output File as Exception for Fund Reporting 
#		 If there is no data available in Detail file then it will 
#		 delete the output File if any existing
#		-Admin/Wf operator Login Information if different across the 
#		 environments, has to be changed in the script accordingly when 
#		 executing in different environments
#		-Any change in environment variables/paths used should be changed
#		 in dot profile
#
# Naming conventions: 
#
#       1. Environment parameter: lower case (dv, it, i2, qa, q2 ,p2, i01, mo......) 
#	2. Folder and workflow names should be in the same case as in Informatica
#	3. Run mode parameters: lower case 
#	
#
# Assumption:	
#	1. The Column Header File should be available in specified location. 
#	   $HOME/server/TgtFiles/performance/fund_ip_index_ColHdr.out
#	2. The DEtail Data file will be generated by ETL session for availability.
#          $HOME/server/TgtFiles/performance/fund_ip_indexdtl.out
#	3. This script is used to be called in IP workflow wf_FundReporting_FirstRate_IndexData
#	   in c_s_m_FundReporting_DSS_FRPINDX immediately after detail data file is generated 
#         
###################################################################################

#!/bin/sh 
#echo 'execution started'
if [ -s $PMTargetFileDir/fr_dw_fund_index_dtl.out ]
then 
cat $PMTargetFileDir/fr_dw_fund_index_ColHdr.out $PMTargetFileDir/fr_dw_fund_index_dtl.out > $PMTargetFileDir/fr_dw_fund_indexaudit.out
else  
	if [ -s $PMTargetFileDir/fr_dw_fund_indexaudit.out ]
	    then
		rm $PMTargetFileDir/fr_dw_fund_indexaudit.out
	fi
fi 
#echo 'execution completed' 
